# Generated by Django 5.0.1 on 2024-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seance",
            name="is_valided",
            field=models.BooleanField(default=False),
        ),
    ]
