# Generated by Django 5.0.1 on 2024-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_patient_user_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=250, verbose_name="Nom et Prénom"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("sujet", models.CharField(max_length=250, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
            ],
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Abonné à la newsletter",
                "verbose_name_plural": "Abonnés à la newsletter",
            },
        ),
    ]
