# Generated by Django 5.0.1 on 2024-01-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_seance_is_valided"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antecedantsmedicaux",
            name="patient",
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="antecedents_medicaux",
            field=models.ManyToManyField(
                blank=True, related_name="patients", to="dashboard.antecedantsmedicaux"
            ),
        ),
    ]
