# Generated by Django 5.0.1 on 2024-01-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_patient_user_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="plandesuivi",
            name="patients",
            field=models.ManyToManyField(
                related_name="plans_de_suivi", to="dashboard.patient"
            ),
        ),
    ]
