# Generated by Django 5.0.1 on 2024-01-09 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_plandesuivi_patients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plandesuivi",
            name="patients",
        ),
        migrations.AddField(
            model_name="plandesuivi",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans_de_suivi",
                to="dashboard.patient",
            ),
        ),
    ]
