# Generated by Django 5.0.1 on 2024-01-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_antecedantsmedicaux_patient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="patient",
        ),
        migrations.AddField(
            model_name="patient",
            name="antecedents_medicaux",
            field=models.ManyToManyField(
                blank=True,
                related_name="patients_antecedents_medicaux",
                to="dashboard.antecedantsmedicaux",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="commandes",
            field=models.ManyToManyField(
                blank=True, related_name="patients", to="dashboard.commande"
            ),
        ),
    ]
