# Generated by Django 5.0.1 on 2024-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0004_remove_commande_patient_patient_antecedents_medicaux_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="seance",
            old_name="is_valided",
            new_name="is_validated",
        ),
        migrations.AddField(
            model_name="seance",
            name="comment",
            field=models.TextField(
                default="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos ut labore rem porro. Totam culpa atque ad! Numquam, deleniti cupiditate est ea, cum repellat saepe animi accusamus aliquid necessitatibus facilis?",
                help_text="Entrez le commentaire de la séance",
                max_length=2048,
                verbose_name="Comment",
            ),
        ),
    ]
