# Generated by Django 5.0.1 on 2024-01-10 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_contactus_newslettersubscriber"),
        ("dashboard", "0004_remove_plandesuivi_patients_plandesuivi_patient"),
    ]

    operations = []
