# Generated by Django 5.0.1 on 2024-01-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_rename_is_valided_seance_is_validated_seance_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="seance",
            name="date_validation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
