# Generated by Django 5.0.1 on 2024-01-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_merge_20240110_0727"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "verbose_name": "Boite à lettre",
                "verbose_name_plural": "Boite à lettre",
            },
        ),
        migrations.AddField(
            model_name="equipement",
            name="conseil",
            field=models.TextField(
                default="",
                help_text="Entrez un bref conseil d'une phrase",
                max_length=510,
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Entrez le type de l'équipement",
                max_length=100,
                verbose_name="Type",
            ),
        ),
    ]
