# Generated by Django 5.0.1 on 2024-01-12 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_contactus_options_equipement_conseil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipement",
            name="quantite",
            field=models.IntegerField(
                default=1,
                help_text="Entrez la quantité disponible de l'équipement",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantité",
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="prix",
            field=models.FloatField(
                help_text="Entrez le prix de l'équipement",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Prix",
            ),
        ),
    ]
