# Generated by Django 5.0.1 on 2024-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_seance_date_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="quartier",
            field=models.CharField(
                blank=True,
                help_text="Entrez le quartier de l'utilisateur",
                max_length=100,
                null=True,
                verbose_name="Quartier",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ville",
            field=models.CharField(
                blank=True,
                help_text="Entrez la ville de l'utilisateur",
                max_length=100,
                null=True,
                verbose_name="Ville",
            ),
        ),
    ]
