# Generated by Django 5.0.1 on 2024-01-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_equipement_quantite_alter_equipement_prix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipement",
            name="conseil",
            field=models.TextField(
                default="",
                help_text="Entrez un bref conseil d'une phrase",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="description",
            field=models.TextField(
                help_text="Entrez la description de l'équipement",
                max_length=255,
                verbose_name="Description",
            ),
        ),
    ]
