# Generated by Django 5.0.1 on 2024-01-29 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_message_room_delete_chat_message_room"),
        ("dashboard", "0007_alter_patient_quartier_alter_patient_ville"),
    ]

    operations = []
